# Generated by Django 4.0.4 on 2022-04-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametype',
            name='game_type_in_room',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='user',
        ),
    ]
