# Generated by Django 4.0.4 on 2022-04-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameType',
        ),
    ]
