# Generated by Django 4.0.4 on 2022-04-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_gametype_game_type_in_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametype',
            old_name='game_types',
            new_name='game_type',
        ),
    ]
