# Generated by Django 4.0.4 on 2022-04-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_remove_roulette_max_bet_remove_roulette_max_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roulette',
            name='game_types',
        ),
    ]
