# Generated by Django 4.0.4 on 2022-04-27 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poker_app.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[poker_app.web.validators.validate_only_letters])),
                ('max_players', models.IntegerField(validators=[poker_app.web.validators.GameMaxPlayersValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
