# Generated by Django 4.0.4 on 2022-04-28 22:06

from django.db import migrations, models
import poker_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poker',
            name='game_types',
            field=models.CharField(blank=True, choices=[('Texas Holdem', 'Texas Holdem'), ('Omaha', 'Omaha')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='poker',
            name='max_bet',
            field=models.IntegerField(default=1, validators=[poker_app.web.validators.MaxBetValidator(200)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poker',
            name='max_players',
            field=models.IntegerField(default=1, validators=[poker_app.web.validators.GameMaxPlayersValidator(5), poker_app.web.validators.GameMinPlayersValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poker',
            name='min_bet',
            field=models.IntegerField(default=1, validators=[poker_app.web.validators.MinBetValidator(2)]),
            preserve_default=False,
        ),
    ]
