# Generated by Django 4.0.4 on 2022-04-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poker',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='poker',
            name='min_bet',
        ),
    ]
