# Generated by Django 4.0.4 on 2022-04-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_poker_game_types_poker_max_bet_poker_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poker',
            name='game_types',
            field=models.CharField(blank=True, choices=[('Texas Holdem', 'texas'), ('Omaha', 'Omaha'), ('Omaha2', 'Omaha2')], default='DO_NOT_SHOW', max_length=12, null=True),
        ),
    ]
