# Generated by Django 4.0.4 on 2022-04-24 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10)),
                ('max_players', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('min_bet', models.IntegerField()),
            ],
        ),
    ]
