# Generated by Django 4.0.4 on 2022-04-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
    ]
