# Generated by Django 4.0.4 on 2022-04-29 08:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import poker_app.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('max_players', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('min_bet', models.IntegerField(validators=[poker_app.web.validators.MinBetValidator(2)])),
                ('max_bet', models.IntegerField(validators=[poker_app.web.validators.MaxBetValidator(20)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
